### ISSUE TITLE
Words per minute calculation is incorrect

### ISSUE THREAD

**Issue by chaughawout** [zedor/TypingTest#1]

**Comment by zedor** [comment]
Could you elaborate please?

**Comment by chaughawout** [comment]
The main issue is that it does not take into account longer words taking more time to type. The correct way to calculate words per minute can be found in [this article](http://www.speedtypingonline.com/typing-equations). The difference between this calculation and the current implementation is that as you continue to type, the words per minute will always lessen.

**Comment by chaughawout** [comment]
This was also addressed in a reddit thread on /r/dota2 a week ago when a link to this minigame's repo was linked. I'd look for the link but I've got some university work I'm doing :/

**Comment by zedor** [comment]
As seen on [this line](https://github.com/zedor/TypingTest/blob/master/src%20TypingTest/TypingTest.as#L183), score is increased by the length of every correctly typed word + the following space, and it is divided by 5 on [this line](https://github.com/zedor/TypingTest/blob/master/src%20TypingTest/TypingTest.as#L128). The calc was changed one day after the reddit thread.

Would this address the issue then?

**Comment by chaughawout** [comment]
Looks like I'm using a slightly older version of the plugin! I'll update, and test then get back to you!

**Comment by zedor** [comment]
Be sure to download the new LX, it's mostly up to date along with ingame leaderboards (except the font issue on them). Also please comment once you test it out so I know whether to close this issue or fix something :)

**Comment by chaughawout** [comment]
Sure thing! :D

**Comment by zedor** [comment]
Please resubmit issue if you think it still persists. I believe it is working correctly.
